# Generated by configure script
variable "REGISTRY_IMAGE" { default = "chocolatefrappe/nginx-modules" }
variable "NGINX_MODULES" { default = "brotli" }
variable "NGINX_VERSION" { default = "stable" }
variable "NGINX_IMAGE_TAG" { default = "nginx:${NGINX_VERSION}" }
variable "NGINX_TTL_IMAGE_TAG" { default = "ttl.sh/alpine-nginx-${NGINX_VERSION}:24h" }

group "default" {
    targets = [
        "alpine-nginx-modules",
        "debian-nginx-modules",
    ]
}

target "nginx-ttl" {
    dockerfile-inline = "FROM nginx:${NGINX_VERSION}"
    platforms = [
        "linux/amd64",
        "linux/arm64",
    ]
    tags = [ "${NGINX_TTL_IMAGE_TAG}" ]
}

target "alpine-nginx-modules" {
    dockerfile = "alpine/Dockerfile"
    args = {
        ENABLED_MODULES = "${NGINX_MODULES}",
        NGINX_VERSION = "${NGINX_VERSION}",
        NGINX_IMAGE_TAG = "${NGINX_IMAGE_TAG}",
    }
    platforms = [
        "linux/amd64",
        "linux/arm64",
    ]
    tags = [
        "${REGISTRY_IMAGE}:${NGINX_VERSION}-alpine-${NGINX_MODULES}"
    ]
}

target "debian-nginx-modules" {
    dockerfile = "debian/Dockerfile"
    args = {
        ENABLED_MODULES = "${NGINX_MODULES}",
        NGINX_VERSION = "${NGINX_VERSION}",
        NGINX_IMAGE_TAG = "${NGINX_IMAGE_TAG}",
    }
    platforms = [
        "linux/amd64",
        "linux/arm64",
    ]
    tags = [
        "${REGISTRY_IMAGE}:${NGINX_VERSION}-${NGINX_MODULES}"
    ]
}
