name: Generate random UUID

on:
  workflow_call:

jobs:
  generate:
    runs-on: ubuntu-latest
    outputs:
      uuid: ${{ steps.uuid.outputs.uuid }}
    steps:
      - name: Generate a one-time UUID
        id: uuid
        run: |
          UUID=$(uuidgen | tr '[:upper:]' '[:lower:]')
          echo "UUID=${UUID}" >> $GITHUB_ENV
          echo "::add-mask::${UUID}"
          echo "uuid=${UUID}" >> $GITHUB_OUTPUT
