FROM scratch

ADD https://raw.githubusercontent.com/nginx/pkg-oss/refs/heads/master/alpine/Makefile.module-acme       /alpine/Makefile.module-acme
ADD https://raw.githubusercontent.com/nginx/pkg-oss/refs/heads/master/debian/Makefile.module-acme       /debian/Makefile.module-acme
ADD https://raw.githubusercontent.com/nginx/pkg-oss/refs/heads/master/contrib/src/nginx-acme/Makefile   /contrib/src/nginx-acme/Makefile
ADD https://raw.githubusercontent.com/nginx/pkg-oss/refs/heads/master/contrib/src/nginx-acme/SHA512SUMS /contrib/src/nginx-acme/SHA512SUMS
ADD https://raw.githubusercontent.com/nginx/pkg-oss/refs/heads/master/contrib/src/nginx-acme/version    /contrib/src/nginx-acme/version
ADD https://raw.githubusercontent.com/nginx/pkg-oss/refs/heads/master/docs/nginx-module-acme.copyright  /docs/nginx-module-acme.copyright
ADD http://raw.githubusercontent.com/nginx/pkg-oss/refs/heads/master/docs/nginx-module-acme.xml         /docs/nginx-module-acme.xml
