name: Release versioned

on:
  push:
    branches:
      - main

  # Runs at 00:00, only on Sunday
  schedule:
    - cron: '0 0 * * SUN'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  generate:
    runs-on: macos-latest
    steps:
      - run: echo "No need to do anything here"

  alpine:
    runs-on: ubuntu-latest
    # continue-on-error: true
    needs: generate
    strategy:
      fail-fast: false
      matrix:
        version:
          - stable
          - mainline
        module:
          - auth-spnego
          - brotli
          - encrypted-session
          - fips-check
          - geoip
          - geoip2
          - headers-more
          - image-filter
          - lua
          - modsecurity
          - ndk
          - njs
          - opentracing
          - passenger
          - perl
          - rtmp
          - set-misc
          - subs-filter
          - xslt
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: chocolatefrappe/nginx-module-${{ matrix.module }}
          tags: type=raw,value=${{ matrix.version }}-alpine
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/bake-action@v3
        env:
          NGINX_VERSION: ${{ matrix.version }}
        with:
          targets: alpine
          files: |
            docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          push: ${{ github.event_name != 'pull_request' }}
      - name: Docker Metadata Summary
        uses: dockerbakery/docker-metadata-summary@v1

  debian:
    runs-on: ubuntu-latest
    # continue-on-error: true
    needs: generate
    strategy:
      fail-fast: false
      matrix:
        version:
          - stable
          - mainline
        module:
          - auth-spnego
          - brotli
          - encrypted-session
          - fips-check
          - geoip
          - geoip2
          - headers-more
          - image-filter
          - lua
          - modsecurity
          - ndk
          - njs
          - opentracing
          - passenger
          - perl
          - rtmp
          - set-misc
          - subs-filter
          - xslt
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: chocolatefrappe/nginx-module-${{ matrix.module }}
          tags: type=raw,value=${{ matrix.version }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/bake-action@v3
        env:
          NGINX_VERSION: ${{ matrix.version }}
        with:
          targets: debian
          files: |
            docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          push: ${{ github.event_name != 'pull_request' }}
      - name: Docker Metadata Summary
        uses: dockerbakery/docker-metadata-summary@v1
