name: Docker

on:
  workflow_call:
    inputs:
      version:
        description: 'The nginx version to build'
        required: true
        type: string
      module:
        description: 'The nginx module to build'
        required: true
        type: string
      targets:
        description: 'The targets for docker-bake.hcl'
        required: true
        type: string
      push:
        description: 'Whether to push the image to Docker Registry'
        required: false
        type: boolean
      tags:
        description: 'The tags for the image'
        required: false
        type: string

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check
        run: |
          jq -ecr ".[\"${{ inputs.module }}\"]" nginx-modules.json
          if [ $? -ne 0 ]; then
            echo "Cannot find module ${{ inputs.module }} in nginx-modules.json"
            exit 1
          fi
  build:
    runs-on: ubuntu-latest
    needs:
      - check
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get module description
        id: module
        run: |
          description=$(jq -cr ".[\"${{ inputs.module }}\"].desc" nginx-modules.json)
          homepage=$(jq -cr ".[\"${{ inputs.module }}\"].homepage" nginx-modules.json)
          echo "description=${description}" >> $GITHUB_OUTPUT
          echo "homepage=${homepage}" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: chocolatefrappe/nginx-modules
          flavor: |
            latest=false
          tags: ${{ inputs.tags }}
          labels: |
            org.opencontainers.image.title=${{ inputs.module }}
            org.opencontainers.image.description=${{ steps.module.outputs.description }}
            org.opencontainers.image.url=${{ steps.module.outputs.homepage }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@v3
        env:
          NGINX_VERSION: ${{ inputs.version }}
          ENABLED_MODULE: ${{ inputs.module }}
        with:
          targets: ${{ inputs.targets }}
          files: |
            docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          push: ${{ inputs.push }}

      - name: Docker Metadata Summary
        uses: dockerbakery/docker-metadata-summary@v1
