name: Docker (matrix)

on:
  workflow_call:
    inputs:
      version:
        description: 'The nginx version to build'
        required: true
        type: string
      targets:
        description: 'The targets for docker-bake.hcl'
        required: true
        type: string
      push:
        description: 'Whether to push the image to Docker Registry'
        required: false
        type: boolean

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Generate modules
      - uses: actions/checkout@v4
      - id: module
        run: echo "module=$(jq -ecr "keys" nginx-modules.json)" >> "$GITHUB_OUTPUT"
    outputs:
      module: ${{ steps.module.outputs.module }}

  build:
    runs-on: ubuntu-latest
    needs: generate
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        module: ${{ fromJson(needs.generate.outputs.module) }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@v6
        env:
          NGINX_VERSION: ${{ inputs.version }}
          NGINX_MODULES: ${{ matrix.module }}
        with:
          targets: ${{ inputs.targets }}
          push: ${{ inputs.push }}
          files: docker-bake.hcl
