name: Docker

on:
  workflow_call:
    inputs:
      version:
        description: 'The nginx version to build'
        required: true
        type: string
      targets:
        description: 'The targets for docker-bake.hcl'
        required: true
        type: string
      module:
        description: 'The nginx modules to build'
        required: true
        type: string
      push:
        description: 'Whether to push the image to Docker Registry'
        required: false
        type: boolean

jobs:
  build:
    name: "${{ inputs.targets }} (${{ inputs.version }}/${{ inputs.module }})"
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@v6
        env:
          NGINX_VERSION: ${{ inputs.version }}
          NGINX_MODULES: ${{ inputs.module }}
        with:
          targets: ${{ inputs.targets }}-nginx-modules
          push: ${{ inputs.push }}
          files: docker-bake.hcl
