name: README.md

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of nginx to generate the README for'
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        description: 'The version of nginx to generate the README for'
        required: true
        type: string

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_PAT }}

      - name: Generate nginx-versions.json
        run: |
          cat <<EOF >nginx-versions.json
          ${{ inputs.version }}
          EOF

      - name: Generate README.md
        run: ./readme.sh

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate README.md
          file_pattern: README.md

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: chocolatefrappe/nginx-modules
