name: Release versioned

on:
  workflow_call:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Generate release versions
      - id: today
        uses: actions-matrix/today@main
      - id: release
        uses: actions-matrix/release-matrix-action@v2
        with:
          search: "nginx"
          limit: 3
          # date: ">=${{ steps.today.outputs.year }}"
          date: ">=2024-04"
      # Generate modules
      - uses: actions/checkout@v4
      - id: module
        run: echo "module=$(jq -ecr "keys" nginx-modules.json)" >> "$GITHUB_OUTPUT"
    outputs:
      versions: ${{ steps.release.outputs.versions }}
      module: ${{ steps.module.outputs.module }}

  prepare:
    needs: generate
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        version: ${{ fromJson(needs.generate.outputs.versions) }}
    steps:
      - name: Creating a short-lived NGINX image at "ttl.sh/nginx-${{ format(matrix.version, '.', '-') }}:24h"...
        uses: docker/bake-action@v6
        env:
          NGINX_VERSION: ${{ matrix.version }}
        with:
          targets: nginx-ttl
          push: true
          files: docker-bake.hcl

  alpine:
    name: alpine
    # continue-on-error: true
    needs:
      - generate
      - prepare
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        version: ${{ fromJson(needs.generate.outputs.versions) }}
        module: ${{ fromJson(needs.generate.outputs.module) }}
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
    with:
      targets: alpine
      version: ${{ matrix.version }}
      module: ${{ matrix.module }}
      push: ${{ github.event_name != 'pull_request' }}

  debian:
    name: debian
    # continue-on-error: true
    needs:
      - generate
      - prepare
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        version: ${{ fromJson(needs.generate.outputs.versions) }}
        module: ${{ fromJson(needs.generate.outputs.module) }}
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
    with:
      targets: debian
      version: ${{ matrix.version }}
      module: ${{ matrix.module }}
      push: ${{ github.event_name != 'pull_request' }}

  generate-readme:
    needs: 
      - generate
      - alpine
      - debian
    permissions:
      contents: write
    uses: ./.github/workflows/readme.yml
    secrets: inherit
    with:
      version: ${{ needs.generate.outputs.versions }}
