name: Release channel

on:
  workflow_call:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - id: release
        run: echo 'version=["stable", "mainline"]' >> "$GITHUB_OUTPUT"
    outputs:
      version: ${{ steps.release.outputs.version }}

  alpine:
    name: alpine
    # continue-on-error: true
    needs:
      - generate
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        version: ${{ fromJson(needs.generate.outputs.version) }}
    uses: ./.github/workflows/docker-build-matrix.yml
    secrets: inherit
    with:
      targets: alpine
      version: ${{ matrix.version }}
      push: ${{ github.event_name != 'pull_request' }}

  debian:
    name: debian
    # continue-on-error: true
    needs:
      - generate
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        version: ${{ fromJson(needs.generate.outputs.version) }}
    uses: ./.github/workflows/docker-build-matrix.yml
    secrets: inherit
    with:
      targets: debian
      version: ${{ matrix.version }}
      push: ${{ github.event_name != 'pull_request' }}
