name: Release canonical

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Generate modules
      - uses: actions/checkout@v4
      - id: module
        run: echo "module=$(jq -ecr "keys_unsorted" nginx-modules.json)" >> "$GITHUB_OUTPUT"

      # Generate release versions
      - id: today
        uses: actions-matrix/today@main
      - id: release
        uses: actions-matrix/release-matrix-action@v2
        with:
          search: "nginx"
          limit: 3
          date: ">=${{ steps.today.outputs.year }}"
      - id: semver
        uses: actions-matrix/semver@v1
        with:
          value: ${{ steps.release.outputs.versions }}
          pattern: "{major}.{minor}"
    outputs:
      version: ${{ steps.semver.outputs.version }}
      module: ${{ steps.module.outputs.module }}


  alpine:
    name: alpine
    # continue-on-error: true
    needs:
      - generate
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        version: ${{ fromJson(needs.generate.outputs.version) }}
        module: ${{ fromJson(needs.generate.outputs.module) }}
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
    with:
      version: ${{ matrix.version }}
      module: ${{ matrix.module }}
      targets: alpine
      tags: |
        type=raw,value=${{ matrix.version }}-alpine-${{ matrix.module }}
      push: ${{ github.event_name != 'pull_request' }}
      generate-summary: true

  debian:
    name: debian
    # continue-on-error: true
    needs:
      - generate
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        version: ${{ fromJson(needs.generate.outputs.version) }}
        module: ${{ fromJson(needs.generate.outputs.module) }}
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
    with:
      version: ${{ matrix.version }}
      module: ${{ matrix.module }}
      targets: debian
      tags: |
        type=raw,value=${{ matrix.version }}-${{ matrix.module }}
      push: ${{ github.event_name != 'pull_request' }}
      generate-summary: true
