name: Release canonical

on:
  push:
    branches:
      - main
    paths:
      - 'alpine/*'
      - 'debian/*'
      - 'modules/*'
      - 'docker-bake.hcl'
      - 'nginx-modules.json'

  # Runs at 00:00, only on Sunday
  schedule:
    - cron: '0 0 * * SUN'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Generate modules
      - uses: actions/checkout@v3
      - id: module
        run: echo "module=$(jq -cr '' nginx-modules.json)" >> "$GITHUB_OUTPUT"
      - id: release
        run: echo 'version=["stable", "mainline"]' >> "$GITHUB_OUTPUT"
    outputs:
      version: ${{ steps.release.outputs.version }}
      module: ${{ steps.module.outputs.module }}

  alpine:
    # continue-on-error: true
    needs:
      - generate
    strategy:
      fail-fast: false
      # max-parallel: 10
      matrix:
        version: ${{ fromJson(needs.generate.outputs.version) }}
        module: ${{ fromJson(needs.generate.outputs.module) }}
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
    with:
      version: ${{ matrix.version }}
      module: ${{ matrix.module }}
      targets: alpine
      tags: |
        type=raw,value=${{ matrix.version }}-alpine-${{ matrix.module }}
      push: ${{ github.event_name != 'pull_request' }}

  debian:
    # continue-on-error: true
    needs:
      - generate
    strategy:
      fail-fast: false
      # max-parallel: 10
      matrix:
        version: ${{ fromJson(needs.generate.outputs.version) }}
        module: ${{ fromJson(needs.generate.outputs.module) }}
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
    with:
      version: ${{ matrix.version }}
      module: ${{ matrix.module }}
      targets: debian
      tags: |
        type=raw,value=${{ matrix.version }}-${{ matrix.module }}
      push: ${{ github.event_name != 'pull_request' }}
