name: Release

on:
  workflow_dispatch:
  # Runs at 00:00, only on Saturday
  schedule:
    - cron: '0 0 * * SAT'
  push:
    branches:
      - main
    paths:
      - 'alpine/**'
      - 'debian/**'
      - 'modules/**'
      - 'docker-bake.hcl'
      - 'nginx-modules.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read
  actions: write

env:
  GH_TOKEN: ${{ github.token}}

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Sleeping for 30 seconds to allow other jobs to start"
          sleep 30

  canonical:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: gh workflow run release-canonical.yml --ref main

  channel:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: gh workflow run release-channel.yml --ref main

  versioned:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: gh workflow run release-versioned.yml --ref main
