name: Release canonical

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Generate release versions
      - id: today
        uses: actions-matrix/today@main
      - id: release
        uses: actions-matrix/release-matrix-action@v2
        with:
          search: "nginx"
          # limit: 3
          # date: ">=${{ steps.today.outputs.year }}"
          date: ">=2024-04"
      - id: semver
        uses: actions-matrix/semver@v1
        with:
          value: ${{ steps.release.outputs.versions }}
          pattern: "{major}.{minor}"
    outputs:
      version: ${{ steps.semver.outputs.version }}


  alpine:
    name: alpine
    # continue-on-error: true
    needs:
      - generate
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        version: ${{ fromJson(needs.generate.outputs.version) }}
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
    with:
      targets: nginx-modules-alpine
      version: ${{ matrix.version }}
      push: ${{ github.event_name != 'pull_request' }}

  debian:
    name: debian
    # continue-on-error: true
    needs:
      - generate
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        version: ${{ fromJson(needs.generate.outputs.version) }}
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
    with:
      targets: nginx-modules-debian
      version: ${{ matrix.version }}
      push: ${{ github.event_name != 'pull_request' }}
