name: Release versioned

on:
  workflow_call:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Generate modules
      - uses: actions/checkout@v4
      - id: module
        run: echo "module=$(jq -ecr "keys_unsorted" nginx-modules.json)" >> "$GITHUB_OUTPUT"

      # Generate release versions
      - id: today
        uses: actions-matrix/today@main
      - id: release
        uses: actions-matrix/release-matrix-action@v2
        with:
          search: "nginx"
          # limit: 2
          # date: ">=${{ steps.today.outputs.year }}"
          date: ">=2024-04"
    outputs:
      versions: ${{ steps.release.outputs.versions }}
      module: ${{ steps.module.outputs.module }}


  alpine:
    name: alpine
    # continue-on-error: true
    needs:
      - generate
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        version: ${{ fromJson(needs.generate.outputs.versions) }}
        module: ${{ fromJson(needs.generate.outputs.module) }}
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
    with:
      version: ${{ matrix.version }}
      module: ${{ matrix.module }}
      targets: alpine
      tags: |
        type=semver,pattern={{version}}-alpine-${{ matrix.module }},value=${{ matrix.version }}
      push: ${{ github.event_name != 'pull_request' }}
      generate-summary: true

  debian:
    name: debian
    # continue-on-error: true
    needs:
      - generate
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        version: ${{ fromJson(needs.generate.outputs.versions) }}
        module: ${{ fromJson(needs.generate.outputs.module) }}
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
    with:
      version: ${{ matrix.version }}
      module: ${{ matrix.module }}
      targets: debian
      tags: |
        type=semver,pattern={{version}}-${{ matrix.module }},value=${{ matrix.version }}
      push: ${{ github.event_name != 'pull_request' }}
      generate-summary: true

  generate-readme:
    needs: 
      - generate
      - alpine
      - debian
    permissions:
      contents: write
    uses: ./.github/workflows/readme.yml
    secrets: inherit
    with:
      version: ${{ needs.generate.outputs.versions }}
