name: Release versioned

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Generate release versions
      - id: today
        uses: actions-matrix/today@main
      - id: release
        uses: actions-matrix/release-matrix-action@v2
        with:
          search: "nginx"
          limit: 3
          date: ">=${{ steps.today.outputs.year }}"
    outputs:
      versions: ${{ steps.release.outputs.versions }}

  alpine:
    name: alpine
    # continue-on-error: true
    needs:
      - generate
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        version: ${{ fromJson(needs.generate.outputs.versions) }}
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
    with:
      targets: nginx-modules-alpine
      version: ${{ matrix.version }}
      push: ${{ github.event_name != 'pull_request' }}

  debian:
    name: debian
    # continue-on-error: true
    needs:
      - generate
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        version: ${{ fromJson(needs.generate.outputs.versions) }}
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
    with:
      targets: nginx-modules-debian
      version: ${{ matrix.version }}
      push: ${{ github.event_name != 'pull_request' }}

  generate-readme:
    needs: 
      - generate
      - alpine
      - debian
    permissions:
      contents: write
    uses: ./.github/workflows/readme.yml
    secrets: inherit
    with:
      version: ${{ needs.generate.outputs.versions }}
