name: Release channel

on:
  workflow_call:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Generate modules
      - uses: actions/checkout@v4
      - id: nginx-versions
        run: echo "versions=" >> "$GITHUB_OUTPUT"
      - id: nginx-modules
        run: echo "modules=$(jq -ecr 'keys | join(",")' nginx-modules.json)" >> "$GITHUB_OUTPUT"
    outputs:
      versions: ${{ steps.nginx-versions.outputs.versions }}
      modules: ${{ steps.nginx-modules.outputs.modules }}

  alpine:
    name: alpine
    # continue-on-error: true
    needs:
      - generate
    uses: ./.github/workflows/use-docker-build.yml
    secrets: inherit
    with:
      targets: alpine
      versions: ${{ needs.generate.outputs.versions }}
      modules: ${{ needs.generate.outputs.modules }}
      push: ${{ github.event_name != 'pull_request' }}

  debian:
    name: debian
    # continue-on-error: true
    needs:
      - generate
    uses: ./.github/workflows/use-docker-build.yml
    secrets: inherit
    with:
      targets: debian
      versions: ${{ needs.generate.outputs.versions }}
      modules: ${{ needs.generate.outputs.modules }}
      push: ${{ github.event_name != 'pull_request' }}
