name: Release channel

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - id: release
        run: echo 'version=["stable", "mainline"]' >> "$GITHUB_OUTPUT"
    outputs:
      version: ${{ steps.release.outputs.version }}

  alpine:
    name: alpine
    # continue-on-error: true
    needs:
      - generate
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        version: ${{ fromJson(needs.generate.outputs.version) }}
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
    with:
      version: ${{ matrix.version }}
      targets: nginx-modules-alpine
      push: ${{ github.event_name != 'pull_request' }}

  debian:
    name: debian
    # continue-on-error: true
    needs:
      - generate
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        version: ${{ fromJson(needs.generate.outputs.version) }}
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
    with:
      version: ${{ matrix.version }}
      targets: nginx-modules-debian
      push: ${{ github.event_name != 'pull_request' }}
