name: Release

on:
  workflow_dispatch:
  # Runs at 00:00, only on Saturday
  schedule:
    - cron: '0 0 * * SAT'
  push:
    branches:
      - main
    paths:
      - 'alpine/**'
      - 'debian/**'
      - 'modules/**'
      - 'docker-bake.hcl'
      - 'nginx-modules.json'

concurrency:
  group: release-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ github.token}}

permissions:
  contents: write
  packages: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate builder matrix
        id: generate-builder
        uses: docker/bake-action/subaction/matrix@v6
        with:
          target: builders
      - name: Generate module matrix
        id: generate-module
        uses: docker/bake-action/subaction/matrix@v6
        with:
          target: modules
    outputs:
      builder-matrix: ${{ steps.generate-builder.outputs.matrix }}
      module-matrix: ${{ steps.generate-module.outputs.matrix }}

  prepare:
    name: prepare
    # continue-on-error: true
    needs:
      - generate
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.generate.outputs.builder-matrix) }}
    uses: ./.github/workflows/use-docker-build.yml
    secrets: inherit
    with:
      targets: ${{ matrix.target }}
      push: ${{ github.event_name != 'pull_request' }}

  build:
    # continue-on-error: true
    needs:
      - generate
      - prepare
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.generate.outputs.module-matrix) }}
    uses: ./.github/workflows/use-docker-build.yml
    secrets: inherit
    with:
      targets: ${{ matrix.target }}
      push: ${{ github.event_name != 'pull_request' }}

  generate-readme:
    needs:
      - generate
      - build
    uses: ./.github/workflows/use-readme.yml
    secrets: inherit
