name: Build NGINX short-lived image

on:
  workflow_call:
    inputs:
      version:
        description: 'The nginx version to build'
        required: true
        type: string

env:
  DOCKER_BUILD_SUMMARY: false
  DOCKER_BUILD_RECORD_UPLOAD: false

jobs:
  build:
    name: Building short-lived NGINX image...
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variants:
          - alpine
          - debian
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/bake-action@v6
        env:
          NGINX_VERSION: ${{ inputs.version }}-alpine
          NGINX_TTL_IMAGE_TAG: ttl.sh/${{ secrets.UUID }}-nginx-module-builder-${{matrix.variants}}-${{ inputs.version }}:24h
        with:
          targets: nginx-module-builder
          push: true
          files: docker-bake.hcl
