name: Docker

on:
  workflow_call:
    inputs:
      version:
        description: 'The nginx version to build'
        required: true
        type: string

jobs:
  build:
    name: Creating a short-lived NGINX image at "ttl.sh/nginx-${{ format(inputs.version, '.', '-') }}:24h"...
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/bake-action@v6
        env:
          NGINX_VERSION: ${{ inputs.version }}
        with:
          targets: nginx-ttl
          push: true
          files: docker-bake.hcl
