name: Docker build

on:
  workflow_call:
    inputs:
      targets:
        description: 'The targets for docker-bake.hcl'
        required: true
        type: string
      version:
        description: 'The nginx version to build'
        required: true
        type: string
      modules:
        description: 'The nginx modules to build'
        type: string
        default: ''
      push:
        description: 'Whether to push the image to Docker Registry'
        required: false
        type: boolean

jobs:
  build:
    name: "build ${{ inputs.targets }} (${{ inputs.version}}) (${{ inputs.modules }})"
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker metadata
        id: docker-meta
        uses: docker/metadata-action@v5

      - name: Build and push
        uses: docker/bake-action@v6
        env:
          NGINX_VERSIONS: ${{ inputs.version }}
          NGINX_MODULES: ${{ inputs.modules }}
        with:
          targets: nginx-modules-${{ inputs.targets }}
          push: ${{ inputs.push }}
          files: |
            docker-bake.hcl
            cwd://${{ steps.docker-meta.outputs.bake-file-labels }}
            cwd://${{ steps.docker-meta.outputs.bake-file-annotations }}
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=min
